//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string THesabcode { get; set; }
        public string TName { get; set; }
        public string Tel { get; set; }
        public string MobileNum { get; set; }
        public string Address { get; set; }
        public decimal ThMandeh { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string FirstName { get; set; }
        public string PhoneNum { get; set; }
        public string SearchField { get; set; }
        public decimal T_Hesan_Extant { get; set; }
    }
}
