//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMap
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<short> VisitorCode { get; set; }
        public string MapColor { get; set; }
        public Nullable<decimal> TargetValue { get; set; }
        public Nullable<decimal> TargetValue1 { get; set; }
        public Nullable<decimal> TargetValue2 { get; set; }
        public Nullable<decimal> TargetValue3 { get; set; }
        public Nullable<decimal> TargetValue4 { get; set; }
        public Nullable<decimal> TargetValue5 { get; set; }
        public Nullable<decimal> TargetValue6 { get; set; }
        public Nullable<decimal> TargetValue7 { get; set; }
        public Nullable<decimal> TargetValue8 { get; set; }
        public Nullable<decimal> TargetValue9 { get; set; }
        public Nullable<decimal> TargetValue10 { get; set; }
        public Nullable<decimal> TargetValue11 { get; set; }
        public Nullable<int> VisitLogCountTarget { get; set; }
        public Nullable<int> VisitLogCountTarget1 { get; set; }
        public Nullable<int> VisitLogCountTarget2 { get; set; }
        public Nullable<int> VisitLogCountTarget3 { get; set; }
        public Nullable<int> VisitLogCountTarget4 { get; set; }
        public Nullable<int> VisitLogCountTarget5 { get; set; }
        public Nullable<int> VisitLogCountTarget6 { get; set; }
        public Nullable<int> VisitLogCountTarget7 { get; set; }
        public Nullable<int> VisitLogCountTarget8 { get; set; }
        public Nullable<int> VisitLogCountTarget9 { get; set; }
        public Nullable<int> VisitLogCountTarget10 { get; set; }
        public Nullable<int> VisitLogCountTarget11 { get; set; }
    }
}
