//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDetails
    {
        public int ID { get; set; }
        public Nullable<int> PInvID { get; set; }
        public string PInv_Code { get; set; }
        public string BarCode { get; set; }
        public string K_Code { get; set; }
        public string K_Name { get; set; }
        public Nullable<double> PK_Amount { get; set; }
        public Nullable<decimal> K_Price { get; set; }
        public Nullable<double> Reduction_p { get; set; }
        public Nullable<decimal> Row_Multi { get; set; }
        public Nullable<decimal> ExtantDetails { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<short> PCompanyID { get; set; }
        public Nullable<int> PBarCodeID { get; set; }
        public Nullable<decimal> RowReduction { get; set; }
        public Nullable<int> RowID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<double> PCsPerUnit { get; set; }
        public Nullable<decimal> K_Price_Marjo { get; set; }
        public Nullable<decimal> OldPriceMarjo { get; set; }
    }
}
