//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPictures
    {
        public int ID { get; set; }
        public string ERPCode { get; set; }
        public byte[] Picture { get; set; }
        public string RootERPCode { get; set; }
    }
}
