//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string ERPCode { get; set; }
        public string BrandERPCode { get; set; }
        public string KArtNo { get; set; }
        public string KBarCode { get; set; }
        public string K_Name { get; set; }
        public decimal K_price_sail { get; set; }
        public decimal K_price_sail2 { get; set; }
        public decimal K_price_sail3 { get; set; }
        public decimal EndUserPrice { get; set; }
        public int ProductID { get; set; }
        public int PcompanyID { get; set; }
        public int PBarCodeID { get; set; }
        public Nullable<double> vat { get; set; }
        public double Mojodi { get; set; }
    }
}
