//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string FactNumber { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string FactDate { get; set; }
        public string OrderDate { get; set; }
        public Nullable<short> VisitorCode { get; set; }
        public string VisitorName { get; set; }
        public Nullable<short> InvMode { get; set; }
        public string K_Name { get; set; }
        public double OrderCount { get; set; }
        public Nullable<double> FactCount { get; set; }
        public Nullable<decimal> KalaPrice { get; set; }
        public Nullable<double> Reduction { get; set; }
        public Nullable<decimal> RowPrice { get; set; }
        public Nullable<decimal> RowRemain { get; set; }
        public Nullable<decimal> FactReduction { get; set; }
        public int Offer { get; set; }
        public string Memo { get; set; }
        public string Description { get; set; }
        public string ReserveField { get; set; }
    }
}
