//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public Nullable<byte> User_Level { get; set; }
        public string Defualt_Part_Code { get; set; }
        public Nullable<short> PartitionCode { get; set; }
        public Nullable<short> AccStep { get; set; }
        public int AnbCode { get; set; }
        public int CashID { get; set; }
        public int MngSailCode { get; set; }
        public string Emp_Code { get; set; }
        public int AcounterCode { get; set; }
        public Nullable<int> PartCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> VisitorCode { get; set; }
        public Nullable<int> DepID { get; set; }
        public string MagnetCardNo { get; set; }
        public string Email { get; set; }
        public Nullable<long> TimeStampID { get; set; }
        public byte[] TimeStampCode { get; set; }
        public byte[] ChangeTSCenter { get; set; }
        public Nullable<int> GUserID { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] ChangeTSCnter { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
