//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THT.OrderManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public short Visitor_Code { get; set; }
        public string Visitor_Name { get; set; }
        public string MobileNo { get; set; }
        public string PocketPassword { get; set; }
    }
}
